<?php
/** @var array $formData */
?>
<!DOCTYPE html>
<html>
<head>
    <title>New Contact Form Submission</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f9;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #333;
            font-size: 24px;
            margin-bottom: 20px;
        }
        p {
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            text-align: center;
            color: #777;
            font-size: 12px;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>New Contact Form Submission</h1>
        <p>A new contact form submission has been received with the following details:</p>
        <table>
            <tr>
                <th>Name</th>
                <td><?= esc($formData['Username']) ?></td>
            </tr>
            <tr>
                <th>Email</th>
                <td><?= esc($formData['Email']) ?></td>
            </tr>
            <tr>
                <th>Phone</th>
                <td><?= esc($formData['Phone']) ?></td>
            </tr>
            <tr>
                <th>Company</th>
                <td><?= esc($formData['Enter_Company']) ?></td>
            </tr>
            <tr>
                <th>Country</th>
                <td><?= esc($formData['Country']) ?></td>
            </tr>
            <tr>
                <th>Message</th>
                <td><?= esc($formData['Message']) ?></td>
            </tr>
        </table>
        <p class="footer">This email was automatically generated by the contact form on our website.</p>
    </div>
</body>
</html>
